---
title: MSCC
timezone: GMT
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
email: naamanh10@gmail.com
description: Manchesters most inclusive road cycling club promoting health and wellbeing.
baseurl: ''
url: http://mscc.naamanhudson.com/
markdown: kramdown
